import { getCache } from '@vercel/functions';
import crypto from 'node:crypto';

export const TTL=21600,HAND=6,SLOTS=3,MAX_MP=15,REACTION_AID=2;
export const cache=getCache({namespace:'isekai-tcg-v050'});
const C={}; const add=(id,c)=>C[id]=c;

const races=[['王国','⚜️'],['森エルフ','🌿'],['岩山ドワーフ','⛏️'],['獣人','🐾'],['魔族','😈'],['竜族','🐉'],['天使','👼'],['不死','💀'],['精霊','🧚'],['海族','🌊'],['砂漠','🏜️'],['影','🌑']];
const roles=['剣士','槍兵','弓兵','騎士','魔導士','司祭','斥候','守衛','狂戦士','忍者','賢者','竜騎士'];
let ui=0;
for(let r=0;r<races.length;r++)for(let j=0;j<roles.length;j++){
  const cost=1+((r*5+j*3)%12); let atk=Math.max(1,cost+((r+j)%3)-1),hp=Math.max(2,cost+2+((r*2+j)%3)-1);
  const c={name:`${races[r][0]}の${roles[j]}`,type:'unit',cost,atk,hp,icon:races[r][1]},t=[];
  if(ui%13===0){c.guard=1;atk=Math.max(1,atk-1);hp+=2;t.push('守護')}
  if(ui%17===5){c.haste=1;atk=Math.max(1,atk-1);hp=Math.max(1,hp-1);t.push('疾走')}
  if(ui%23===9){c.lifesteal=1;atk=Math.max(1,atk-1);t.push('吸血')}
  if(ui%29===11){c.pierce=1;hp=Math.max(1,hp-1);t.push('貫通')}
  if(ui%31===7){c.draw=1;atk=Math.max(1,atk-1);hp=Math.max(1,hp-1);t.push('召喚時1枚ドロー')}
  if(ui%37===15){c.heal=3;hp=Math.max(1,hp-1);t.push('召喚時HP3回復')}
  if(ui%41===19){c.mpGain=1;atk=Math.max(1,atk-1);t.push('召喚時MP1回復')}
  c.atk=atk;c.hp=hp;c.text=t.length?t.join('・')+'。':'標準的なユニット。';add(`u${ui++}`,c)
}
const els=[['火炎','🔥'],['氷結','❄️'],['雷鳴','⚡'],['聖光','☀️'],['暗黒','🌘'],['風刃','🌪️']],forms=['弾','矢','槍','刃','砲','波'];let di=0;
for(let e=0;e<els.length;e++)for(let f=0;f<forms.length;f++){const cost=1+((e*2+f)%10),unitOnly=(e+f)%3===0,power=cost+(unitOnly?2:1)+(cost>=8?1:0);add(`d${di++}`,{name:`${els[e][0]}${forms[f]}`,type:'damage',cost,power,icon:els[e][1],unitOnly,text:`${unitOnly?'敵ユニット':'敵ユニットか本体'}に${power}ダメージ。`})}
const an=['吹雪','火炎嵐','雷雲','聖域崩壊','闇の奔流','竜巻','地割れ','星雨','毒霧','大津波','隕石群','終末波'],ai=['🌨️','🔥','🌩️','✨','🌑','🌪️','🌋','🌠','☠️','🌊','☄️','💥'];
for(let i=0;i<12;i++){const cost=3+(i%10),power=Math.floor(cost/2)+1;add(`ao${i}`,{name:an[i],type:'aoe',cost,power,icon:ai[i],text:`敵ユニット全体に${power}ダメージ。`})}
const hn=['小治癒','癒しの風','聖水','生命魔法','女神の祈り','再生の光','大治癒','世界樹の露','生命の奔流','天使の抱擁','奇跡の聖歌','創世の息吹'];
for(let i=0;i<12;i++){const cost=1+(i%10),power=Math.min(20,cost*2+1);add(`h${i}`,{name:hn[i],type:'heal',cost,power,icon:'💚',text:`HPを${power}回復。`})}
const dn=['思考加速','賢者の洞察','古文書解読','星読み','神託','未来視','記憶の泉','大賢者の講義','禁書解読','運命観測','天啓','世界記録'];
for(let i=0;i<12;i++){const power=1+(i%4),cost=Math.max(1,power*2-1+(i%3===0?0:1));add(`dr${i}`,{name:dn[i],type:'draw',cost,power,icon:'📚',text:`${power}枚ドロー。`})}
const bn=['鼓舞','戦意高揚','炎の祝福','雷の加護','獣王の咆哮','勇者の加護','狂戦士化','英雄覚醒','竜血強化','聖戦の号令','魔王の威圧','神威付与','限界突破','剣聖の教え','戦神降臨'];
for(let i=0;i<15;i++){const power=1+(i%5),cost=power+(i>=10?1:0);add(`b${i}`,{name:bn[i],type:'buff',cost,power,icon:'📣',text:`味方ユニット1体のATK+${power}。`})}
const wn=['鉄の剣','鋼の槍','炎剣','氷刃','雷槍','聖銀剣','魔剣','竜牙槍','勇者の剣','王家の大剣','天界槍','終焉剣'];
for(let i=0;i<12;i++){const power=1+(i%6),cost=Math.max(1,power+(power>=4?1:0));add(`ea${i}`,{name:wn[i],type:'equipA',cost,power,icon:'⚔️',text:`味方ユニット1体のATK+${power}。`})}
const arn=['革鎧','鉄盾','鋼鎧','精霊外套','聖騎士盾','竜鱗盾','ミスリル鎧','王家の鎧','天使の羽衣','魔王鎧','竜王盾','神盾'];
for(let i=0;i<12;i++){const cost=1+(i%6),power=cost*2+(i%2);add(`eh${i}`,{name:arn[i],type:'equipH',cost,power,icon:'🛡️',text:`味方ユニット1体の最大HPとHP+${power}。`})}
const sn=['精霊召喚','魔狼召喚','ゴーレム召喚','竜雛召喚','天使召喚','亡霊召喚','獣王召喚','炎魔召喚','海獣召喚','影獣召喚','聖獣召喚','古竜召喚'],si=['🧚','🐺','🗿','🐉','👼','👻','🦁','👹','🐙','🌑','🦄','🐲'];
for(let i=0;i<12;i++){const cost=2+(i%7);let atk=Math.max(2,cost),hp=cost+1;const haste=i%4===1,guard=i%4===2;if(haste){atk=Math.max(1,atk-1);hp=Math.max(1,hp-1)}if(guard){atk=Math.max(1,atk-1);hp+=2}add(`s${i}`,{name:sn[i],type:'summon',cost,icon:si[i],summonAtk:atk,summonHp:hp,summonHaste:haste,summonGuard:guard,text:`${atk}/${hp}${haste?' 疾走':''}${guard?' 守護':''}の召喚ユニットを出す。`})}
const rb=[['reactReduce','障壁','🫧'],['reactCancel','回避','🌀'],['reactReflect','反射','🪞'],['reactCounter','反撃','⚔️']];let ri=0;
for(const[type,label,icon]of rb)for(let i=0;i<10;i++){let cost,power=0,text;if(type==='reactReduce'){cost=i<2?0:1+(i%3);power=2+cost*2+Math.floor(i/5);text=`受けるダメージ-${power}。`}else if(type==='reactCancel'){cost=2+(i%2);text='攻撃を完全に無効化。'}else if(type==='reactReflect'){cost=2+(i%3);power=2+(i%5);text=`攻撃を無効化し、相手本体へ${power}ダメージ。`}else{cost=i<2?0:1+(i%3);power=2+cost+(i%3);text=`攻撃者へ${power}ダメージ。攻撃自体は受ける。`}add(`r${ri++}`,{name:`${label}${i+1}`,type,cost,power,icon,text})}
export const CARD_COUNT=Object.keys(C).length;
const IDS=Object.keys(C),by=f=>IDS.filter(id=>f(C[id])),UNITS=by(c=>c.type==='unit'),DAMAGE=by(c=>['damage','aoe'].includes(c.type)),UTILITY=by(c=>['heal','draw'].includes(c.type)),SUPPORT=by(c=>['buff','equipA','equipH'].includes(c.type)),SUMMONS=by(c=>c.type==='summon'),REACTIONS=by(c=>c.type.startsWith('react'));
const OPEN=[['女神の祝福','👑','最大HPとHP+5','hp5'],['魔力の祝福','🔷','開始時の最大MP+2','mana2'],['知恵の加護','📘','2枚ドロー','draw2'],['守護の加護','🛡️','守護ユニットを手札へ','guard'],['風神の加護','🌪️','疾走ユニットを手札へ','wind'],['武具の支給','⚔️','武器カードを手札へ','sword']];
const EARLY=[['聖なる泉','⛲','HP5回復','heal5'],['魔力鉱脈','💎','最大MP+1','maxmp1'],['傭兵との出会い','🤝','低コストユニットを無料召喚','merc'],['禁断の宝箱','🧰','HP-2、攻撃魔法と障壁を獲得','risk'],['古代図書館','📚','2枚ドロー','draw2'],['王国武器庫','🏰','武器を獲得','sword']];
const MID=[['覚醒の兆し','🌟','味方全員ATK+1','atk1'],['竜の契約','🐉','大型ユニットを獲得','dragon'],['大賢者の助言','🧙','上3枚から1枚選択','discover'],['血の契約','🩸','HP-3、最大MP+2','blood'],['城塞の加護','🏯','味方全員HP+2','hpteam'],['雷神の恩寵','⚡','攻撃魔法2枚を獲得','lightning']];
const LATE=[['戦神の号令','⚔️','味方全員ATK+2','atk2'],['魔力奔流','🌌','最大MP+3・MP3回復','maxmp3'],['世界樹の祝福','🌳','HP8回復・味方HP+2','tree'],['終焉の契約','☠️','HP-5、大型ユニットを獲得','final'],['天界の援軍','👼','大型守護ユニットを獲得','angel'],['星読みの予言','🌠','全体魔法と回復を獲得','stars'],['限界突破','💥','HP-4、味方ATK+3','limit']];
export const isReaction=t=>!!t&&t.startsWith('react'),otherIndex=i=>i?0:1,roomKey=c=>'room:'+String(c||'').toUpperCase(),playerIndex=(r,t)=>r.players.findIndex(p=>p&&p.token===t),token=()=>crypto.randomBytes(12).toString('base64url'),roomCode=()=>Array.from({length:6},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join('');
export function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function take(pool,n){const o=[];let b=shuffle(pool);while(o.length<n){if(!b.length)b=shuffle(pool);o.push(b.pop())}return o}
export function buildDeck(){const ul=UNITS.filter(id=>C[id].cost<=3),um=UNITS.filter(id=>C[id].cost>=4&&C[id].cost<=6),uh=UNITS.filter(id=>C[id].cost>=7&&C[id].cost<=9),ut=UNITS.filter(id=>C[id].cost>=10),dl=DAMAGE.filter(id=>C[id].cost<=4),dh=DAMAGE.filter(id=>C[id].cost>=5),xl=UTILITY.filter(id=>C[id].cost<=4),xh=UTILITY.filter(id=>C[id].cost>=5),sl=SUPPORT.filter(id=>C[id].cost<=4),sh=SUPPORT.filter(id=>C[id].cost>=5);return shuffle([...take(ul,14),...take(um,12),...take(uh,8),...take(ut,6),...take(dl,8),...take(dh,6),...take(xl,6),...take(xh,4),...take(sl,6),...take(sh,4),...take(SUMMONS,6),...take(REACTIONS,10)])}
export function makeCard(id){return{iid:crypto.randomBytes(5).toString('hex'),cardId:id,...C[id]}}
export function makePlayer(name,t=null,list=null){const d=shuffle(list||buildDeck()),h=d.splice(0,HAND).map(makeCard);return{name:(name||'冒険者').slice(0,16),token:t||token(),hp:30,maxHp:30,mp:0,maxMp:0,hand:h,deck:d,field:Array(SLOTS).fill(null),opening:null,discover:null,awakening:0,awakened:false}}
export function publicCard(c){if(!c)return null;const{iid,cardId,name,type,cost,atk,hp,maxHp,icon,text,guard,haste,lifesteal,pierce,power,unitOnly,exhausted,sick,draw,heal,mpGain}=c;return{iid,cardId,name,type,cost,atk,hp,maxHp,icon,text,guard:!!guard,haste:!!haste,lifesteal:!!lifesteal,pierce:!!pierce,power,unitOnly:!!unitOnly,exhausted:!!exhausted,sick:!!sick,draw,heal,mp:mpGain}}
export function log(r,msg,actor=null,kind='info'){r.log||=[];r.log.push({t:Date.now(),msg,actor,kind});if(r.log.length>40)r.log=r.log.slice(-40)}
export async function loadRoom(code){return cache.get(roomKey(code))} export async function saveRoom(r){r.version=(r.version||0)+1;await cache.set(roomKey(r.code),r,{ttl:TTL});return r}
export function draw(p,n){while(n-->0&&p.deck.length)p.hand.push(makeCard(p.deck.shift()))}
function us(u){return u?Math.max(0,u.atk||0)+Math.max(0,u.hp||0)+(u.guard?2:0)+(u.haste?1:0)+(u.lifesteal?2:0)+(u.pierce?1:0):0}
function pressure(r,i){const p=r.players[i],o=r.players[otherIndex(i)];if(!p||!o)return 0;return Math.max(0,o.hp-p.hp)*2+Math.max(0,o.field.reduce((s,u)=>s+us(u),0)-p.field.reduce((s,u)=>s+us(u),0))+Math.max(0,o.hand.length-p.hand.length)*2}
export function addAwakening(p,n){if(!p||p.awakened)return;p.awakening=Math.min(100,(p.awakening||0)+Math.max(0,Math.floor(n)))}
function turnAwaken(r,i){const p=r.players[i];if(!p||p.awakened)return;const pr=pressure(r,i),o=r.players[otherIndex(i)];let g=pr>=10?Math.min(36,8+Math.floor(pr/3)):0;if(p.hp<=12)g+=8;if(p.field.filter(Boolean).length===0&&o?.field.filter(Boolean).length>=2)g+=8;addAwakening(p,g);if(g>0)log(r,`${p.name}の逆境覚醒ゲージ+${g}。`,i,'awakening')}
export function killIfDead(r,p,s,a){const u=p.field[s];if(u&&u.hp<=0){log(r,`${u.name}が撃破された。`,a,'battle');p.field[s]=null;addAwakening(p,6);return 1}return 0}
export function checkWin(r){r.players.forEach((p,i)=>{if(p&&p.hp<=0&&r.status!=='ended'){r.status='ended';r.phase='ended';r.winner=otherIndex(i);r.rematch=[0,0];log(r,`${r.players[r.winner].name}の勝利！`,r.winner,'result')}})}
export function startTurn(r){const p=r.players[r.active];turnAwaken(r,r.active);p.maxMp=Math.min(MAX_MP,p.maxMp+1);p.mp=p.maxMp;p.field.forEach(u=>{if(u){u.exhausted=0;u.sick=0}});if(!p.deck.length){r.status='ended';r.phase='ended';r.winner=otherIndex(r.active);r.rematch=[0,0];return}const n=Math.min(2,p.deck.length);draw(p,n);r.phase='main';log(r,`TURN ${r.turnNo}：${p.name}が${n}枚ドロー。`,r.active,'turn')}
function pick(pool,n){return shuffle(pool).slice(0,n).map((x,i)=>({id:`${x[3]}-${i}-${crypto.randomBytes(2).toString('hex')}`,title:x[0],icon:x[1],text:x[2],effect:x[3]}))}
export function maybeEvent(r){r.events||=[];if(r.turnNo>=3&&r.turnNo%3===0&&!r.events.includes(r.turnNo)){r.events.push(r.turnNo);const pool=r.turnNo<=6?EARLY:r.turnNo<=12?MID:LATE;r.phase='event';r.gate={choices:[pick(pool,3),pick(pool,3)],selected:[null,null]};log(r,`運命イベント発生！ TURN ${r.turnNo}`,null,'event');return true}return false}
export function nextTurn(r){if(!maybeEvent(r))startTurn(r)}
function randomByType(type){const a=IDS.filter(id=>C[id].type===type);return makeCard(a[Math.floor(Math.random()*a.length)])} function randomUnit(fn){const a=UNITS.filter(id=>fn(C[id])),p=a.length?a:UNITS;return makeCard(p[Math.floor(Math.random()*p.length)])}
export function applyEventEffect(r,i,e){const p=r.players[i];let s,u;switch(e){case'hp5':p.maxHp+=5;p.hp+=5;break;case'mana2':p.maxMp=Math.min(MAX_MP,p.maxMp+2);p.mp=Math.min(p.maxMp,p.mp+2);break;case'draw2':draw(p,2);break;case'guard':p.hand.push(randomUnit(x=>x.guard));break;case'wind':p.hand.push(randomUnit(x=>x.haste));break;case'sword':p.hand.push(randomByType('equipA'));break;case'heal5':p.hp=Math.min(p.maxHp,p.hp+5);break;case'maxmp1':p.maxMp=Math.min(MAX_MP,p.maxMp+1);p.mp=Math.min(p.maxMp,p.mp+1);break;case'merc':s=p.field.findIndex(x=>!x);u=randomUnit(x=>x.cost<=2);u.maxHp=u.hp;u.sick=1;u.exhausted=0;s<0?p.hand.push(u):p.field[s]=u;break;case'risk':p.hp-=2;p.hand.push(randomByType('damage'),randomByType('reactReduce'));break;case'atk1':p.field.forEach(x=>{if(x)x.atk+=1});break;case'dragon':p.hand.push(randomUnit(x=>x.cost>=8));break;case'discover':{const ids=p.deck.splice(0,Math.min(3,p.deck.length));p.discover=ids.map(makeCard);break}case'blood':p.hp-=3;p.maxMp=Math.min(MAX_MP,p.maxMp+2);p.mp=Math.min(p.maxMp,p.mp+2);break;case'hpteam':p.field.forEach(x=>{if(x){x.maxHp=(x.maxHp||x.hp)+2;x.hp+=2}});break;case'lightning':p.hand.push(randomByType('damage'),randomByType('damage'));break;case'atk2':p.field.forEach(x=>{if(x)x.atk+=2});break;case'maxmp3':p.maxMp=Math.min(MAX_MP,p.maxMp+3);p.mp=Math.min(p.maxMp,p.mp+3);break;case'tree':p.hp=Math.min(p.maxHp,p.hp+8);p.field.forEach(x=>{if(x){x.maxHp=(x.maxHp||x.hp)+2;x.hp+=2}});break;case'final':p.hp-=5;p.hand.push(randomUnit(x=>x.cost>=10));break;case'angel':p.hand.push(randomUnit(x=>x.guard&&x.cost>=6));break;case'stars':p.hand.push(randomByType('aoe'),randomByType('heal'));break;case'limit':p.hp-=4;p.field.forEach(x=>{if(x)x.atk+=3});break}}
export function openingChoices(){return[pick(OPEN,3),pick(OPEN,3)]}
export function makeView(r,i){const me=r.players[i],op=r.players[otherIndex(i)];let last=null;for(let n=(r.log||[]).length-1;n>=0;n--)if(r.log[n].actor===otherIndex(i)){last=r.log[n];break}const v={code:r.code,status:r.status,phase:r.phase,version:r.version,turnNo:r.turnNo,matchNo:r.matchNo||1,active:r.active,you:i,winner:r.winner??null,log:r.log||[],lastOpponentAction:last,cardCount:CARD_COUNT,maxMpLimit:MAX_MP,me:{name:me.name,hp:me.hp,maxHp:me.maxHp,mp:me.mp,maxMp:me.maxMp,hand:me.hand.map(publicCard),deckCount:me.deck.length,field:me.field.map(publicCard)},opponent:op?{name:op.name,hp:op.hp,maxHp:op.maxHp,mp:op.mp,maxMp:op.maxMp,handCount:op.hand.length,deckCount:op.deck.length,field:op.field.map(publicCard)}:null,openingChoices:null,eventChoices:null,discoverChoices:null,pendingAttack:null,rematch:r.status==='ended'?{you:!!r.rematch?.[i],opponent:!!r.rematch?.[otherIndex(i)]}:null,awakening:{gauge:Math.floor(me.awakening||0),ready:!me.awakened&&(me.awakening||0)>=100,used:!!me.awakened,canUse:!me.awakened&&(me.awakening||0)>=100&&r.status==='playing'&&r.phase==='main'&&r.active===i}};if(r.status==='opening')v.openingChoices=r.openChoices[i];if(r.gate)v.eventChoices=r.gate.selected[i]?[]:r.gate.choices[i];if(me.discover)v.discoverChoices=me.discover.map(publicCard);if(r.attack){v.pendingAttack={...r.attack,attacker:publicCard(r.players[r.attack.ap].field[r.attack.as])};if(r.attack.dp===i)v.reactionCards=me.hand.filter(c=>isReaction(c.type)&&c.cost<=me.mp+REACTION_AID).map(publicCard)}return v}
export function resetMatch(r){const old=r.players,list=buildDeck();r.deckList=list;r.players=old.map(p=>makePlayer(p.name,p.token,list));r.matchNo=(r.matchNo||1)+1;r.active=Math.floor(Math.random()*2);r.turnNo=1;r.status='opening';r.phase='opening';r.winner=null;r.attack=null;r.gate=null;r.events=[];r.rematch=[0,0];r.openChoices=openingChoices();r.log=[];log(r,`第${r.matchNo}戦開始。`,null,'system')}
export function summonTokenFromCard(c){return{iid:token(),cardId:'token-'+c.cardId,name:c.name.replace('召喚','')+'の使い魔',type:'unit',cost:0,atk:c.summonAtk,hp:c.summonHp,maxHp:c.summonHp,haste:!!c.summonHaste,guard:!!c.summonGuard,icon:c.icon,text:c.text,sick:!c.summonHaste,exhausted:0}}
export function resolveReaction(r,i,iid=null){if(r.phase!=='reaction'||!r.attack||r.attack.dp!==i)throw Error('INVALID_PHASE');const p=r.players[i],a=r.attack,ap=r.players[a.ap],at=ap.field[a.as];let d=Math.max(0,Number(a.damage)||0),cancel=false;if(iid){const h=p.hand.findIndex(x=>x.iid===iid);if(h<0)throw Error('INVALID_CARD');const c=p.hand[h];if(!isReaction(c.type))throw Error('INVALID_CARD');const pay=Math.max(0,c.cost-REACTION_AID);if(pay>p.mp)throw Error('NO_MP');p.mp-=pay;p.hand.splice(h,1);if(c.type==='reactReduce')d=Math.max(0,d-c.power);if(c.type==='reactCancel')cancel=true;if(c.type==='reactReflect'){cancel=true;ap.hp-=c.power;addAwakening(ap,c.power*2)}if(c.type==='reactCounter'&&at){at.hp-=c.power;killIfDead(r,ap,a.as,i)}log(r,`${p.name}が「${c.name}」でリアクション。`,i,'reaction')}if(!cancel){if(a.target.kind==='player'){p.hp-=d;addAwakening(p,Math.min(20,d*2))}else if(a.target.kind==='unit'){const s=Number(a.target.slot),u=p.field[s];if(u){const before=u.hp;u.hp-=d,extra=Math.max(0,d-before),k=killIfDead(r,p,s,a.ap);if(k&&at?.pierce&&extra){p.hp-=extra;addAwakening(p,Math.min(16,extra*2))}}}else throw Error('INVALID_TARGET');if(at?.lifesteal)ap.hp=Math.min(ap.maxHp,ap.hp+2)}r.attack=null;r.phase='main';log(r,cancel?'攻撃は無効化。':`攻撃結果：${d}ダメージ。`,cancel?i:a.ap,'battle');checkWin(r)}
export function applyAwakening(r,i,choice){const p=r.players[i];if(r.status!=='playing'||r.phase!=='main'||r.active!==i)throw Error('NOT_YOUR_ACTION');if(p.awakened||(p.awakening||0)<100)throw Error('AWAKENING_NOT_READY');if(!['rebirth','uprising','destiny'].includes(choice))throw Error('INVALID_CHOICE');if(choice==='rebirth'){p.hp=Math.min(p.maxHp,p.hp+10);draw(p,2);p.mp=Math.min(p.maxMp,p.mp+2);log(r,`${p.name}が逆境覚醒「再起の光」を発動！`,i,'awakening')}else if(choice==='uprising'){p.field.forEach(u=>{if(u){u.atk+=2;u.maxHp=(u.maxHp||u.hp)+2;u.hp+=2}});p.mp=Math.min(p.maxMp,p.mp+4);log(r,`${p.name}が逆境覚醒「反攻の号令」を発動！`,i,'awakening')}else{const u={iid:token(),cardId:'awakening-fate',name:'運命の守護獣',type:'unit',cost:0,atk:6,hp:7,maxHp:7,guard:1,haste:1,icon:'🌌',text:'逆境覚醒で現れる6/7守護・疾走。',sick:0,exhausted:0},s=p.field.findIndex(x=>!x);s>=0?p.field[s]=u:p.hand.push(u);draw(p,1);log(r,`${p.name}が逆境覚醒「運命召喚」を発動！`,i,'awakening')}p.awakened=true;p.awakening=0}
export function json(res,status,data){res.status(status);res.setHeader('Cache-Control','no-store');return res.json(data)}
